name: Resolve LeetCode Daily Question

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v3
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Run script
      run: npm run start

    # - name: Commit and push changes
    #   run: |
    #     git config --global user.name 'melon95'
    #     git config --global user.email 'lijunwork95@gmail.com'
    #     git status
    #     git add -A
    #     git commit -m "feat 🦈: today's daily leetcode question added"
    #     git push https://${{ secrets.GITHUB_TOKEN }}@github.com/melon95/leetcode-daily-question.git HEAD:main
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}